import streamlit as st
from typing import *
import json
import sys
import time
import subprocess
import traceback
from tempfile import NamedTemporaryFile


oai_schema = {
    "type": "function",
    "function": {
        "name": "execute_python_code",
        "description": "Use this function to execute the generated code which requires internet access or external API access", 
        "parameters": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "description": "The python code generated by the code interpretor"
                }
            },
            "required": ["code"],
        }
    }
}

def get_oai_schema():
    schema = oai_schema
    return schema

def execute_python_code(s: str) -> str:
    with NamedTemporaryFile(suffix=".py", delete=False) as temp_file:
        temp_file_name = temp_file.name
        temp_file.write(s.encode("utf-8"))
        temp_file.flush()
    try:
        result = subprocess.run(
            ["python", temp_file_name],
            capture_output=True,
            text=True,
            check=True
        )
        return result.stdout
    except subprocess.CalledProcessError as e:
        return e.stderr
    finally:
        import os
        os.remove(temp_file_name)