[openai]
api_key_magicbook = "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"
api_key_general = "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"
assistant_key = "asst_VpVEYDp6jGDgnMsELF65KAor"
assistant_key_sf = "asst_4CL8RZJcsgG84JSR5CcNcDwW"
assistant_key_json_schema = "asst_K1CcnQHT6HCrBGEWiAf89mJD"
assistant_key_docstring = "asst_7QLZrRg2BnpJGwC28WwDEAH3"
assistant_key_magicbook1 = "asst_ntuQ9wWQWVR0SynxMPLO04Ne"
assistant_key_magicbook2 = "asst_f9LcmBeJRI1VeVk4d1gQ0V79"
assistant_key_magicbookmaster = "asst_DV5R4twArmt1qHwDEKJwUXYM"
assistant_key_threadselector = "asst_xvrwbCbcnRK59KsMw8V9OZgo"
model_vision = "gpt-4-1106-vision"
model_assistant = "gpt-4-1106-preview"
model_gpt_turbo_long = "gpt-3.5-turbo-16k-0613"
model_gpt_turbo_normal = "gpt-3.5-turbo-0613"
model_dalle = "dall-e-3"
parameters_image_size = "1024x1024"
parameters_iterations = 1
parameters_temperature = 0



[connections.supabase]
SUPABASE_URL = "https://plpfcrglastmmqjiluoc.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBscGZjcmdsYXN0bW1xamlsdW9jIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwMzA4NTM1OCwiZXhwIjoyMDE4NjYxMzU4fQ.E7gJbyy5P7WTIpDAI7_HWs-GYssmf7rER263zH_vPr0"

[assembly]
api_key = "16f91e9f91374b4194905334087febc1"

[salesforce]
sfuser = "michael.zozulia@almalasers.com"
sfcred = "EverlyQuinn#7665"
sftoken = "8VY2ZFvXya0eyI1oGCMOZeVc"


[powerautomate]
paSendEmail = "https://prod-82.westus.logic.azure.com:443/workflows/161736b6d81f439096d0452bd1c9b082/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=5qrhisEBUZH0Okbxxl0686qdj9-UyNpVo4fELrELPf8"
HTTP_URL_COMMS = "https://prod-82.westus.logic.azure.com:443/workflows/161736b6d81f439096d0452bd1c9b082/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=5qrhisEBUZH0Okbxxl0686qdj9-UyNpVo4fELrELPf8" 


[supabase]
url = "https://plpfcrglastmmqjiluoc.supabase.co"
api_key_public = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBscGZjcmdsYXN0bW1xamlsdW9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDMwODUzNTgsImV4cCI6MjAxODY2MTM1OH0.Eyf0SfqPfgTENC9dqvAT0Tf3c76TwHTpU4J0z2iweSk"
api_key_private = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBscGZjcmdsYXN0bW1xamlsdW9jIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwMzA4NTM1OCwiZXhwIjoyMDE4NjYxMzU4fQ.E7gJbyy5P7WTIpDAI7_HWs-GYssmf7rER263zH_vPr0"



[zapier]
api_key = "sk-ak-WH14PbyWET9ZgoVWErGmT3zdDu"


[theodds]
api_key = "6b94ab1d81d71ea87b64473a1519fefd"

[tavily]
api_key = "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"


[other]
REPLICATE_API_KEY = "r8_3NSkiwpBKmC85pU61cXmYooqc35t5Ft0Dn5Cc"
SERP_API_KEY = '5cea8ad504d40e86139eeed0626cba900b102ed17704b48becabf94c2c0b0b99'
EXTRACTOR_API_KEY = '77da7c56abc8fa6c702c9d9644810ddc75c00b43'